Reconnecting sometimes picks a hub that doesn't exist.
I've gotten these errors periodically and this should resolve them.

/Path/to/project/node_modules/seaport/index.js:45
        var c = net.connect.call(null, hubs[conIx].port, hubs[conIx].host);
                                                  ^
TypeError: Cannot read property 'port' of undefined
    at reconnect [as _onTimeout] (/Path/to/project/node_modules/seaport/index.js:45:51)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)